[tool.autoflake]
# make changes to files instead of printing diffs
in-place = true
# drill down directories recursively
recursive = true
# remove all unused imports (not just those from the standard library)
remove-all-unused-imports = true
# exclude __init__.py when removing unused imports
ignore-init-module-imports = true
# remove unused variables
remove-unused-variables = true

[tool.isort]
# multiline output option: there are 10 options
multi_line_output = 3
# max line-length whithin the project
line_length = 140
# includes a trailing comma on multi line imports that include parentheses.
include_trailing_comma= true
# number of lines after imports section
lines_after_imports = 2

[tool.black]
# max line-length whithin the project
line-length = 140
# version of Python within the project
target-version = ['py310']

